# Premier League Match Outcome Prediction - EDA

Exploration of Premier League match data from the 2016/17 season to 2025/26

In [1]:
# imports

import pandas as pd
from pathlib import Path

In [6]:
DATA_DIR = Path("../data/raw")
files = sorted(DATA_DIR.glob("E0_*.csv"))

print(f"found {len(files)} files")

found 10 files

In [8]:
# combine data

dfs = []

for file in files:
    df_season = pd.read_csv(file)
    
    season = file.stem.replace("E0_", "")
    df_season["Season"] = season
    
    dfs.append(df_season)
    
df = pd.concat(dfs, ignore_index = True)

C:\Users\kushs\AppData\Local\Temp\ipykernel_34276\2488241897.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_season["Season"] = season
C:\Users\kushs\AppData\Local\Temp\ipykernel_34276\2488241897.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_season["Season"] = season

In [14]:
# basic insepctions
df.sample(5)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
1456,E0,01/07/2020,Everton,Leicester,2,1,H,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2721,E0,30/09/2023,Everton,Luton,1,2,A,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3308,E0,26/02/2025,Tottenham,Man City,0,1,A,0,1,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3419,E0,25/05/2025,Wolves,Brentford,1,1,D,0,1,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1945,E0,18/09/2021,Norwich,Watford,1,3,A,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,E0,13/08/16,Burnley,Swansea,0,1,A,0,0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,13/08/16,Crystal Palace,West Brom,0,1,A,0,0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,13/08/16,Everton,Tottenham,1,1,D,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,13/08/16,Hull,Leicester,2,1,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,13/08/16,Man City,Sunderland,2,1,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.tail()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
3795,E0,24/05/2026,Man City,Aston Villa,1,2,A,1,0,H,...,6.75,1.4,5.25,7.00,1.40,5.25,6.00,1.40,5.25,6.00
3796,E0,24/05/2026,Nott'm Forest,Bournemouth,1,1,D,1,0,H,...,1.90,3.5,3.80,1.95,3.40,3.60,2.05,3.40,3.60,2.05
3797,E0,24/05/2026,Sunderland,Chelsea,2,1,H,1,0,H,...,1.96,3.4,3.70,2.05,3.40,3.60,2.05,3.40,3.50,2.05
3798,E0,24/05/2026,Tottenham,Everton,1,0,H,1,0,H,...,4.10,1.9,3.40,4.33,1.85,3.50,4.20,1.85,3.50,4.00
3799,E0,24/05/2026,West Ham,Leeds,3,0,H,0,0,D,...,4.35,1.7,4.10,4.50,1.73,4.20,4.33,1.70,4.00,4.20

In [17]:
df.columns.tolist()

['Div',
 'Date',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'LBH',
 'LBD',
 'LBA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'VCH',
 'VCD',
 'VCA',
 'Bb1X2',
 'BbMxH',
 'BbAvH',
 'BbMxD',
 'BbAvD',
 'BbMxA',
 'BbAvA',
 'BbOU',
 'BbMx>2.5',
 'BbAv>2.5',
 'BbMx<2.5',
 'BbAv<2.5',
 'BbAH',
 'BbAHh',
 'BbMxAHH',
 'BbAvAHH',
 'BbMxAHA',
 'BbAvAHA',
 'PSCH',
 'PSCD',
 'PSCA',
 'Season',
 'Time',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'IWCH',
 'IWCD',
 'IWCA',
 'WHCH',
 'WHCD',
 'WHCA',
 'VCCH',
 'VCCD',
 'VCCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA',
 'BFH',
 'BFD',
 'BFA',
 '1XBH',
 '1XBD',
 '1XBA',
 'BFEH',
 'BFED',
 'BFEA',
 'BFE>2.5',
 'BFE<2.5',
 'BFEAHH',
 'BFEAHA',
 'BFCH',
 'BFCD',
 'BFCA',
 '1XBCH',
 '1XBCD',
 '1XBCA',
 'BFECH',
 'BFECD',
 'BFECA',
 'BFEC>2.5',
 'BFEC<2.5',
 'BFECAHH',
 'BFECAHA',
 'BFDH',
 'BFDD',
 'BFDA',
 'BMGMH',
 'BMGMD',
 'BMGMA',
 'BVH',
 'BVD',
 'BVA',
 'CLH',
 'CLD',
 'CLA',
 'BFDCH',
 'BFDCD',
 'BFDCA',
 'BMGMCH',
 'BMGMCD',
 'BMGMCA',
 'BVCH',
 'BVCD',
 'BVCA',
 'CLCH',
 'CLCD',
 'CLCA',
 'LBCH',
 'LBCD',
 'LBCA']

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3800 entries, 0 to 3799
Columns: 181 entries, Div to LBCA
dtypes: float64(156), int64(16), str(9)
memory usage: 5.4 MB

In [ ]:
# basic structure
df["Season"].value_counts().sort_index()

Season
1617    380
1718    380
1819    380
1920    380
2021    380
2122    380
2223    380
2324    380
2425    380
2526    380
Name: count, dtype: int64

In [21]:
df["FTR"].value_counts()

FTR
H    1696
A    1221
D     883
Name: count, dtype: int64

In [ ]:
# data quality, missing data
df.isna().sum()

Div            0
Date           0
HomeTeam       0
AwayTeam       0
FTHG           0
            ...
CLCD        3540
CLCA        3540
LBCH        3519
LBCD        3519
LBCA        3519
Length: 181, dtype: int64

In [23]:
# data quality, duplicates
df.duplicated().sum()

np.int64(0)

In [31]:
# data quality, count of home teams
num_home_teams = len(sorted(df["HomeTeam"].unique()))
print(f"Number of Unique Home Teams: {num_home_teams}")

Number of Unique Home Teams: 34

In [32]:
# data quality, count of away teams
num_away_teams = len(sorted(df["AwayTeam"].unique()))
print(f"Number of Unique Away Teams: {num_away_teams}")

Number of Unique Away Teams: 34

In [ ]:
# needs converting
df["Date"].dtype

In [34]:
df.describe().T

       count       mean       std   min      25%    50%   75%   max
FTHG  3800.0   1.555263  1.313304  0.00   1.0000   1.00   2.0   9.0
FTAG  3800.0   1.279737  1.207771  0.00   0.0000   1.00   2.0   9.0
HTHG  3800.0   0.697895  0.847582  0.00   0.0000   0.00   1.0   5.0
HTAG  3800.0   0.564211  0.780172  0.00   0.0000   0.00   1.0   5.0
HS    3800.0  13.867105  5.685582  0.00  10.0000  13.00  17.0  37.0
...      ...        ...       ...   ...      ...    ...   ...   ...
CLCD   260.0   3.941077  0.967823  3.00   3.4000   3.60   4.2  10.0
CLCA   260.0   3.835615  2.515854  1.17   2.2375   3.10   4.6  21.0
LBCH   281.0   2.654911  1.450373  1.11   1.7000   2.25   3.2  13.0
LBCD   281.0   3.918114  0.933933  3.00   3.4000   3.60   4.2  10.0
LBCA   281.0   3.764626  2.381839  1.17   2.2000   3.10   4.5  19.0

[172 rows x 8 columns]