# Premier League Match Outcome Prediction - EDA

Exploration of Premier League match data from the 2016/17 season to 2025/26

In [48]:
# imports

import pandas as pd
from pathlib import Path
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
DATA_DIR = Path("../data/raw")
files = sorted(DATA_DIR.glob("E0_*.csv"))

print(f"found {len(files)} files")

found 10 files

In [3]:
# combine data

dfs = []

for file in files:
    df_season = pd.read_csv(file)
    
    season = file.stem.replace("E0_", "")
    df_season["Season"] = season
    
    dfs.append(df_season)
    
df = pd.concat(dfs, ignore_index = True)

C:\Users\kushs\AppData\Local\Temp\ipykernel_22196\2488241897.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_season["Season"] = season
C:\Users\kushs\AppData\Local\Temp\ipykernel_22196\2488241897.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_season["Season"] = season

In [4]:
# basic insepctions
df.sample(5)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
1281,E0,03/12/2019,Burnley,Man City,1,4,A,0,1,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,E0,26/02/17,Tottenham,Stoke,4,0,H,4,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
946,E0,26/12/2018,Man United,Huddersfield,3,1,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3064,E0,31/08/2024,Leicester,Aston Villa,1,2,A,0,1,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2578,E0,15/04/2023,Everton,Fulham,1,3,A,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,E0,13/08/16,Burnley,Swansea,0,1,A,0,0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,13/08/16,Crystal Palace,West Brom,0,1,A,0,0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,13/08/16,Everton,Tottenham,1,1,D,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,13/08/16,Hull,Leicester,2,1,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,13/08/16,Man City,Sunderland,2,1,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.tail()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
3795,E0,24/05/2026,Man City,Aston Villa,1,2,A,1,0,H,...,6.75,1.4,5.25,7.00,1.40,5.25,6.00,1.40,5.25,6.00
3796,E0,24/05/2026,Nott'm Forest,Bournemouth,1,1,D,1,0,H,...,1.90,3.5,3.80,1.95,3.40,3.60,2.05,3.40,3.60,2.05
3797,E0,24/05/2026,Sunderland,Chelsea,2,1,H,1,0,H,...,1.96,3.4,3.70,2.05,3.40,3.60,2.05,3.40,3.50,2.05
3798,E0,24/05/2026,Tottenham,Everton,1,0,H,1,0,H,...,4.10,1.9,3.40,4.33,1.85,3.50,4.20,1.85,3.50,4.00
3799,E0,24/05/2026,West Ham,Leeds,3,0,H,0,0,D,...,4.35,1.7,4.10,4.50,1.73,4.20,4.33,1.70,4.00,4.20

In [7]:
df.columns.tolist()

['Div',
 'Date',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'LBH',
 'LBD',
 'LBA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'VCH',
 'VCD',
 'VCA',
 'Bb1X2',
 'BbMxH',
 'BbAvH',
 'BbMxD',
 'BbAvD',
 'BbMxA',
 'BbAvA',
 'BbOU',
 'BbMx>2.5',
 'BbAv>2.5',
 'BbMx<2.5',
 'BbAv<2.5',
 'BbAH',
 'BbAHh',
 'BbMxAHH',
 'BbAvAHH',
 'BbMxAHA',
 'BbAvAHA',
 'PSCH',
 'PSCD',
 'PSCA',
 'Season',
 'Time',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'IWCH',
 'IWCD',
 'IWCA',
 'WHCH',
 'WHCD',
 'WHCA',
 'VCCH',
 'VCCD',
 'VCCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA',
 'BFH',
 'BFD',
 'BFA',
 '1XBH',
 '1XBD',
 '1XBA',
 'BFEH',
 'BFED',
 'BFEA',
 'BFE>2.5',
 'BFE<2.5',
 'BFEAHH',
 'BFEAHA',
 'BFCH',
 'BFCD',
 'BFCA',
 '1XBCH',
 '1XBCD',
 '1XBCA',
 'BFECH',
 'BFECD',
 'BFECA',
 'BFEC>2.5',
 'BFEC<2.5',
 'BFECAHH',
 'BFECAHA',
 'BFDH',
 'BFDD',
 'BFDA',
 'BMGMH',
 'BMGMD',
 'BMGMA',
 'BVH',
 'BVD',
 'BVA',
 'CLH',
 'CLD',
 'CLA',
 'BFDCH',
 'BFDCD',
 'BFDCA',
 'BMGMCH',
 'BMGMCD',
 'BMGMCA',
 'BVCH',
 'BVCD',
 'BVCA',
 'CLCH',
 'CLCD',
 'CLCA',
 'LBCH',
 'LBCD',
 'LBCA']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3800 entries, 0 to 3799
Columns: 181 entries, Div to LBCA
dtypes: float64(156), int64(16), str(9)
memory usage: 5.4 MB

In [9]:
# basic structure
df["Season"].value_counts().sort_index()

Season
1617    380
1718    380
1819    380
1920    380
2021    380
2122    380
2223    380
2324    380
2425    380
2526    380
Name: count, dtype: int64

In [10]:
df["FTR"].value_counts()

FTR
H    1696
A    1221
D     883
Name: count, dtype: int64

In [11]:
# data quality, missing data
df.isna().sum()

Div            0
Date           0
HomeTeam       0
AwayTeam       0
FTHG           0
            ...
CLCD        3540
CLCA        3540
LBCH        3519
LBCD        3519
LBCA        3519
Length: 181, dtype: int64

In [12]:
# data quality, duplicates
df.duplicated().sum()

np.int64(0)

In [13]:
# data quality, count of home teams
num_home_teams = len(sorted(df["HomeTeam"].unique()))
print(f"Number of Unique Home Teams: {num_home_teams}")

Number of Unique Home Teams: 34

In [14]:
# data quality, count of away teams
num_away_teams = len(sorted(df["AwayTeam"].unique()))
print(f"Number of Unique Away Teams: {num_away_teams}")

Number of Unique Away Teams: 34

In [15]:
# needs converting
df["Date"].dtype

In [16]:
df.describe().T

       count       mean       std   min      25%    50%   75%   max
FTHG  3800.0   1.555263  1.313304  0.00   1.0000   1.00   2.0   9.0
FTAG  3800.0   1.279737  1.207771  0.00   0.0000   1.00   2.0   9.0
HTHG  3800.0   0.697895  0.847582  0.00   0.0000   0.00   1.0   5.0
HTAG  3800.0   0.564211  0.780172  0.00   0.0000   0.00   1.0   5.0
HS    3800.0  13.867105  5.685582  0.00  10.0000  13.00  17.0  37.0
...      ...        ...       ...   ...      ...    ...   ...   ...
CLCD   260.0   3.941077  0.967823  3.00   3.4000   3.60   4.2  10.0
CLCA   260.0   3.835615  2.515854  1.17   2.2375   3.10   4.6  21.0
LBCH   281.0   2.654911  1.450373  1.11   1.7000   2.25   3.2  13.0
LBCD   281.0   3.918114  0.933933  3.00   3.4000   3.60   4.2  10.0
LBCA   281.0   3.764626  2.381839  1.17   2.2000   3.10   4.5  19.0

[172 rows x 8 columns]

In [17]:
sorted(df["HomeTeam"].unique())

['Arsenal',
 'Aston Villa',
 'Bournemouth',
 'Brentford',
 'Brighton',
 'Burnley',
 'Cardiff',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Ipswich',
 'Leeds',
 'Leicester',
 'Liverpool',
 'Luton',
 'Man City',
 'Man United',
 'Middlesbrough',
 'Newcastle',
 'Norwich',
 "Nott'm Forest",
 'Sheffield United',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Tottenham',
 'Watford',
 'West Brom',
 'West Ham',
 'Wolves']

In [18]:
# date type conversion

df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
df["Date"].dtype

C:\Users\kushs\AppData\Local\Temp\ipykernel_22196\3755935012.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

dtype('<M8[us]')

In [19]:
df["Date"].dtype

dtype('<M8[us]')

In [20]:
pd.read_csv(files[0])["Date"].sample(10)

238    05/02/17
291    02/04/17
95     29/10/16
340    30/04/17
193    02/01/17
275    18/03/17
200    14/01/17
47     18/09/16
146    11/12/16
4      13/08/16
Name: Date, dtype: str

In [21]:
df["Date"] = pd.to_datetime(df["Date"], format="%d,%m,%y")
df["Date"].dtypes

dtype('<M8[us]')

In [22]:
# verify change

print("Earliest date: ", df["Date"].min())
print("Latest date: ", df["Date"].max())

Earliest date:  2016-08-13 00:00:00
Latest date:  2026-05-24 00:00:00

In [23]:
df["Date"].isna().sum()

np.int64(0)

In [25]:
for i, col in enumerate(df.columns):
    print(i+1, col)

1 Div
2 Date
3 HomeTeam
4 AwayTeam
5 FTHG
6 FTAG
7 FTR
8 HTHG
9 HTAG
10 HTR
11 Referee
12 HS
13 AS
14 HST
15 AST
16 HF
17 AF
18 HC
19 AC
20 HY
21 AY
22 HR
23 AR
24 B365H
25 B365D
26 B365A
27 BWH
28 BWD
29 BWA
30 IWH
31 IWD
32 IWA
33 LBH
34 LBD
35 LBA
36 PSH
37 PSD
38 PSA
39 WHH
40 WHD
41 WHA
42 VCH
43 VCD
44 VCA
45 Bb1X2
46 BbMxH
47 BbAvH
48 BbMxD
49 BbAvD
50 BbMxA
51 BbAvA
52 BbOU
53 BbMx>2.5
54 BbAv>2.5
55 BbMx<2.5
56 BbAv<2.5
57 BbAH
58 BbAHh
59 BbMxAHH
60 BbAvAHH
61 BbMxAHA
62 BbAvAHA
63 PSCH
64 PSCD
65 PSCA
66 Season
67 Time
68 MaxH
69 MaxD
70 MaxA
71 AvgH
72 AvgD
73 AvgA
74 B365>2.5
75 B365<2.5
76 P>2.5
77 P<2.5
78 Max>2.5
79 Max<2.5
80 Avg>2.5
81 Avg<2.5
82 AHh
83 B365AHH
84 B365AHA
85 PAHH
86 PAHA
87 MaxAHH
88 MaxAHA
89 AvgAHH
90 AvgAHA
91 B365CH
92 B365CD
93 B365CA
94 BWCH
95 BWCD
96 BWCA
97 IWCH
98 IWCD
99 IWCA
100 WHCH
101 WHCD
102 WHCA
103 VCCH
104 VCCD
105 VCCA
106 MaxCH
107 MaxCD
108 MaxCA
109 AvgCH
110 AvgCD
111 AvgCA
112 B365C>2.5
113 B365C<2.5
114 PC>2.5
115 PC<2.5
116 MaxC>2.5
117 MaxC<2.5
118 AvgC>2.5
119 AvgC<2.5
120 AHCh
121 B365CAHH
122 B365CAHA
123 PCAHH
124 PCAHA
125 MaxCAHH
126 MaxCAHA
127 AvgCAHH
128 AvgCAHA
129 BFH
130 BFD
131 BFA
132 1XBH
133 1XBD
134 1XBA
135 BFEH
136 BFED
137 BFEA
138 BFE>2.5
139 BFE<2.5
140 BFEAHH
141 BFEAHA
142 BFCH
143 BFCD
144 BFCA
145 1XBCH
146 1XBCD
147 1XBCA
148 BFECH
149 BFECD
150 BFECA
151 BFEC>2.5
152 BFEC<2.5
153 BFECAHH
154 BFECAHA
155 BFDH
156 BFDD
157 BFDA
158 BMGMH
159 BMGMD
160 BMGMA
161 BVH
162 BVD
163 BVA
164 CLH
165 CLD
166 CLA
167 BFDCH
168 BFDCD
169 BFDCA
170 BMGMCH
171 BMGMCD
172 BMGMCA
173 BVCH
174 BVCD
175 BVCA
176 CLCH
177 CLCD
178 CLCA
179 LBCH
180 LBCD
181 LBCA

In [31]:
missing_pct = df.isna().mean().sort_values(ascending=False)

missing_pct.head(50)

CLCH        0.931579
CLCA        0.931579
CLCD        0.931579
LBCH        0.926053
LBCD        0.926053
LBCA        0.926053
CLD         0.925789
CLH         0.925789
CLA         0.925789
1XBA        0.902368
1XBD        0.902368
1XBH        0.902368
BVCH        0.902105
BVCA        0.902105
BFDCD       0.902105
BFDCH       0.902105
BFDCA       0.902105
BVCD        0.902105
BVH         0.900526
BMGMA       0.900526
BVA         0.900526
BMGMD       0.900526
BMGMH       0.900526
BVD         0.900526
BFDH        0.900263
BFD         0.900263
BFH         0.900263
BFDD        0.900263
BFA         0.900263
BFDA        0.900263
1XBCA       0.900000
BFCA        0.900000
BMGMCA      0.900000
1XBCH       0.900000
BFCH        0.900000
BFCD        0.900000
1XBCD       0.900000
BMGMCD      0.900000
BMGMCH      0.900000
BFE>2.5     0.806053
BFE<2.5     0.806053
BFEC>2.5    0.805789
BFEC<2.5    0.805789
BFECA       0.805789
BFECAHH     0.805789
BFECAHA     0.805789
BFECH       0.805789
BFECD       0.805789
BFEAHA      0.805263
BFEH        0.805263
dtype: float64

In [42]:
missing_pct.sort_values(ascending=False).head(50)

CLCH        0.931579
CLCA        0.931579
CLCD        0.931579
LBCH        0.926053
LBCD        0.926053
LBCA        0.926053
CLD         0.925789
CLH         0.925789
CLA         0.925789
1XBA        0.902368
1XBD        0.902368
1XBH        0.902368
BVCH        0.902105
BVCA        0.902105
BFDCD       0.902105
BFDCH       0.902105
BFDCA       0.902105
BVCD        0.902105
BVH         0.900526
BMGMA       0.900526
BVA         0.900526
BMGMD       0.900526
BMGMH       0.900526
BVD         0.900526
BFDH        0.900263
BFD         0.900263
BFH         0.900263
BFDD        0.900263
BFA         0.900263
BFDA        0.900263
1XBCA       0.900000
BFCA        0.900000
BMGMCA      0.900000
1XBCH       0.900000
BFCH        0.900000
BFCD        0.900000
1XBCD       0.900000
BMGMCD      0.900000
BMGMCH      0.900000
BFE>2.5     0.806053
BFE<2.5     0.806053
BFEC>2.5    0.805789
BFEC<2.5    0.805789
BFECA       0.805789
BFECAHH     0.805789
BFECAHA     0.805789
BFECH       0.805789
BFECD       0.805789
BFEAHA      0.805263
BFEH        0.805263
dtype: float64

In [43]:
missing_pct.tail(50).sort_values()

HR          0.000000
AS          0.000000
HST         0.000000
AST         0.000000
B365H       0.000000
B365A       0.000000
B365D       0.000000
Referee     0.000000
AR          0.000000
HTR         0.000000
HTAG        0.000000
HTHG        0.000000
FTR         0.000000
FTAG        0.000000
Season      0.000000
AwayTeam    0.000000
HomeTeam    0.000000
Date        0.000000
Div         0.000000
HF          0.000000
AF          0.000000
HC          0.000000
AY          0.000000
HY          0.000000
AC          0.000000
HS          0.000000
FTHG        0.000000
BWH         0.037632
BWA         0.037632
BWD         0.037632
PSA         0.044737
PSCA        0.044737
PSD         0.044737
PSH         0.044737
PSCD        0.044737
PSCH        0.044737
WHH         0.123947
WHD         0.123947
WHA         0.123947
VCA         0.200000
VCH         0.200000
VCD         0.200000
IWH         0.247895
IWD         0.247895
IWA         0.247895
AvgC>2.5    0.300000
AvgCAHA     0.300000
AHCh        0.300000
MaxCA       0.300000
AvgCH       0.300000
dtype: float64

In [30]:
print("0% missing:", (missing_pct == 0).sum())
print("0–10% missing:", ((missing_pct > 0) & (missing_pct < 0.10)).sum())
print("10–50% missing:", ((missing_pct >= 0.10) & (missing_pct < 0.50)).sum())
print("50–90% missing:", ((missing_pct >= 0.50) & (missing_pct < 0.90)).sum())
print("90%+ missing:", (missing_pct >= 0.90).sum())

0% missing: 27
0–10% missing: 9
10–50% missing: 65
50–90% missing: 41
90%+ missing: 39

## Exploring Target Feature

In [46]:
df['FTR'].value_counts()

FTR
H    1696
A    1221
D     883
Name: count, dtype: int64